---
kind: pipeline
type: docker
name: position-simulator
trigger:
  branch:
    - main
  event:
    - push
    - custom
steps:
  - name: clone
    image: plugins/git
    settings:
      depth: 50
  

