kind: pipeline
type: docker
name: simulator
trigger:
  branch:
    - main
  event:
    - push
    - custom
steps:
  - name: build
    image: maven:3.8.4-jdk-11
    commands:
      - cd k8s-fleetman-position-simulator
      - mvn clean install
  - name: test
    image: maven:3.8.4-jdk-11
    commands:
      - cd k8s-fleetman-position-simulator
      - mvn test
  

