---
kind: pipeline
type: docker
name: simulator
trigger:
  branch:
    - main
  event:
    - push
    - custom
steps:
  - name: build
    image: maven:3.8.4-openjdk-17-slim
    commands:
      - cd k8s-fleetman-position-simulator
      - mvn clean install
      - docker cp 2c16a27cbc4d:/drone/src/k8s-fleetman-position-simulator/target/dependency-check-report.html ~/Desktop
  - name: test
    image: maven:3.8.4-openjdk-17-slim
    commands:
      - cd k8s-fleetman-position-simulator
      - mvn test
  - name: dependency_check
    image: owasp/dependency-check:latest
    commands:
      - dependency-check.sh --scan /drone/src/k8s-fleetman-position-simulator
   
