kind: pipeline
type: docker
name: simulator
trigger:
  branch:
    - main
  event:
    - push
    - custom
steps:
  - name: build
    image: maven:3.8.4-openjdk-17-slim
    commands:
      - cd k8s-fleetman-position-simulator
      - mvn clean install
  - name: test
    image: maven:3.8.4-openjdk-17-slim
    commands:
      - cd k8s-fleetman-position-simulator
      - mvn test
  - name: dependency_check
    image: owasp/dependency-check:latest
    commands:
    - /usr/share/dependency-check/bin/dependency-check.sh --scan /k8s-fleetman-position-simulator --project k8s-fleetman-position-simulator --out /drone/src/dependency-check-report.html --failOnCVSS 0
