kind: pipeline
type: docker
name: position-simulator

steps:
  - name: clone
    image: plugins/git
    settings:
      depth: 50

  - name: build
    image: maven:3.8.4-jdk-11
    commands:
      - mvn clean install

  - name: test
    image: maven:3.8.4-jdk-11
    commands:
      - mvn test

